import type { Metadata } from 'next';
import './globals.css';
import { Providers } from '@/app/providers';
import { Navbar } from '@/widgets/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="max-w-[1024px] mx-auto p-6">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
